- name: Run pre_deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
  ansible.builtin.import_playbook: ./hooks.yml

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
  - name: Create and provision external computes
    ansible.builtin.include_role:
      name: libvirt_manager
      tasks_from: deploy_edpm_compute.yml

  - name: Call predeploy
    ansible.builtin.include_role:
      name: edpm_prepare


- name: Run post_deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
  ansible.builtin.import_playbook: ./hooks.yml
